# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  branch: '$(Build.SourceBranchName)'
  repository: balintbako/plex

stages:
- stage: Build
  displayName: Build image
  variables:
    tags: |
      latest
      armv7
      armhf
      ubuntu-16-latest
      ubuntu-16.04
      plex-latest
      plex-1.22.1.0
      $(branch)
      $(tag)
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CmdLine@2
      displayName: Enable QEMU
      inputs:
        script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'logout'
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'login'        
    - task: Docker@2
      displayName: Build and Push an image
      inputs:
        repository: $(repository)
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tags)